version: '4.1'

services:
  myapp-mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: myapp-mailhog
    ports:
      - "8125:8025"
    restart: unless-stopped

  myapp-mysql:
    image: 'mysql:8.0'
    container_name: myapp-mysql
    working_dir: /var/www/myapp
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
      - ./cakephp:/var/www/myapp
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "8107:3306"  # Changed from 8106 to 8107 to avoid conflicts
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped

  myapp-nginx:
    image: 'nginx:alpine'
    container_name: myapp-nginx
    working_dir: /var/www/myapp
    volumes:
      - ./cakephp:/var/www/myapp
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8180:80"
    depends_on:
      - myapp-php-fpm
    restart: unless-stopped

  myapp-php-fpm:
    build: ./php-fpm
    container_name: myapp-php-fpm
    working_dir: /var/www/myapp
    volumes:
      - ./cakephp:/var/www/myapp
      - ./php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    depends_on:
      - myapp-mysql
      - myapp-mailhog
    restart: unless-stopped
